import { Footer } from './components/Footer/Footer';
import { Navbar } from './components/Navbar/Navbar';
import './globals.css';

export const metadata = {
  title: 'MARKFLIX',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  try {
    return (
      <html lang="en">
        <body>
          <Navbar />

          {children}

          <Footer />
        </body>
      </html>
    );
  } catch (err) {}
}
